begin;

-- =====================================================================
-- 055  fuel_invoice_records.sort_order  -  a real, guaranteed row order.
--
--  WHY: rows pasted together all share one created_at and have random uuid ids,
--       so "entry_date, created_at, id" had no stable order for them.
--
--  HOW THE ORDER IS GUARANTEED (not by luck):
--    * sort_order is a bigint IDENTITY (BY DEFAULT) - a number from a sequence,
--      so it only ever grows.
--    * Before a paste is saved, the page calls  reserve_invoice_sort_orders(n):
--      it takes n numbers from that sequence, in increasing order, inside one
--      call, and returns them as an array.
--    * The page puts number k on the k-th pasted row and sends them with the rows.
--      So the stored order is exactly the paste order, whatever order Postgres
--      happens to insert the rows in.
--    * A UNIQUE index stops two rows from ever sharing a number.
--    * A row inserted without a number (SQL editor, an older page) simply takes
--      the next sequence value, i.e. it goes to the end.
--
--  Existing rows are numbered ONCE here:
--      PetroApp first, then Futurehub (any other source after them);
--      inside a source: entry_date, then invoice_number as a number, then as text.
--
--  ONE transaction: if anything fails, nothing changes.
--  Run it ONCE, after 055_verify_before.sql looked right.
-- =====================================================================


-- 1) Safety: stop if it was already run.
do $$
begin
  if exists (select 1 from information_schema.columns
              where table_schema = 'public' and table_name = 'fuel_invoice_records'
                and column_name = 'sort_order') then
    raise exception 'STOP: fuel_invoice_records.sort_order already exists.';
  end if;
end $$;


-- 2) The column. Existing rows get provisional numbers here; step 4 replaces them.
--    (Brief table lock + rewrite - the table is small.)
alter table public.fuel_invoice_records
  add column sort_order bigint generated by default as identity;


-- 3) Keep the normalising trigger quiet while the existing rows are renumbered,
--    so nothing but sort_order changes in them (it is switched back on in step 6).
alter table public.fuel_invoice_records disable trigger fuel_invoice_records_before_write;


-- 4) Number the existing rows 1..N in the agreed order.
with ranked as (
  select id,
         row_number() over (
           order by case data_source when 'PetroApp' then 1 when 'Futurehub' then 2 else 3 end,
                    data_source,
                    entry_date,
                    case when invoice_number ~ '^[0-9]{1,18}$' then invoice_number::numeric end nulls last,
                    invoice_number,
                    id
         ) as rn
  from public.fuel_invoice_records
)
update public.fuel_invoice_records r
set sort_order = ranked.rn
from ranked
where r.id = ranked.id;


-- 5) Uniqueness + the next number for new rows = N + 1.
create unique index fuel_invoice_records_sort_order_key
  on public.fuel_invoice_records (sort_order);

do $$
declare v_max bigint;
begin
  select coalesce(max(sort_order), 0) into v_max from public.fuel_invoice_records;
  execute format('alter table public.fuel_invoice_records alter column sort_order restart with %s', v_max + 1);
end $$;


-- 6) Trigger back on.
alter table public.fuel_invoice_records enable trigger fuel_invoice_records_before_write;


-- 7) Safety checks: every row numbered, numbers 1..N with no gap or repeat,
--    trigger enabled again.
do $$
declare v_rows bigint; v_distinct bigint; v_min bigint; v_max bigint; v_trg "char";
begin
  select count(*), count(distinct sort_order), min(sort_order), max(sort_order)
    into v_rows, v_distinct, v_min, v_max
  from public.fuel_invoice_records;
  if v_rows <> v_distinct then
    raise exception 'STOP: % rows but % distinct sort_order values.', v_rows, v_distinct;
  end if;
  if v_rows > 0 and (v_min <> 1 or v_max <> v_rows) then
    raise exception 'STOP: sort_order runs % .. % for % rows (expected 1 .. N).', v_min, v_max, v_rows;
  end if;
  select tgenabled into v_trg from pg_trigger
   where tgrelid = 'public.fuel_invoice_records'::regclass and tgname = 'fuel_invoice_records_before_write';
  if v_trg is distinct from 'O' then
    raise exception 'STOP: the normalising trigger is not enabled again.';
  end if;
end $$;


-- 8) Reserve n sort numbers for a paste: increasing, taken in one call.
--    Admins only (the same people who can insert invoices). SECURITY DEFINER so it
--    can use the sequence; it does nothing else.
create or replace function public.reserve_invoice_sort_orders(p_count integer)
returns bigint[]
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_seq text := pg_get_serial_sequence('public.fuel_invoice_records', 'sort_order');
  v_out bigint[] := '{}';
  i integer;
begin
  if not private.is_admin() then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  if p_count is null or p_count < 1 or p_count > 20000 then
    raise exception 'p_count must be between 1 and 20000' using errcode = '22023';
  end if;
  -- One paste at a time: a second call waits here until the first has finished
  -- (the lock is released automatically when this call's transaction ends), so every
  -- paste gets a consecutive block of numbers and two pastes never interleave.
  perform pg_advisory_xact_lock(hashtext('reserve_invoice_sort_orders'));
  for i in 1 .. p_count loop
    v_out := v_out || nextval(v_seq);
  end loop;
  return v_out;
end;
$$;

revoke all on function public.reserve_invoice_sort_orders(integer) from public, anon;
grant execute on function public.reserve_invoice_sort_orders(integer) to authenticated;

notify pgrst, 'reload schema';

commit;
